  'use strict';
  angular.module('myMPCSApp', ['ui.router',
                               'myMPCSApp.filterController',
                               'myMPCSApp.sortController',
                               'myMPCSApp.emailValidation',
                               'myMPCSApp.telephoneValidation',
                               'myMPCSApp.zipCodeValidation',
                               'myMPCSApp.capitalizeFilter',
                               'myMPCSApp.formatMDNFilter',
                               'myMPCSApp.factory',
                               'myMPCSApp.service',
                               'myMPCSApp.config',
                               'myMPCSApp.apiFactory',
                               'myMPCSApp.commonUtil',
                               'myMPCSApp.urlUtils',
                               'myMPCSApp.apiController',
                               'myMPCSApp.exceptionFactory',
                               'myMPCSApp.exceptionService',
                               'myMPCSApp.exceptionController',
                               'myMPCSApp.searchController',
                               'myMPCSApp.searchService',
                               'myMPCSApp.searchFactory',
                               ]);
